INSERT INTO [UAT-TEHR].[dbo].[Gen_Reserves]
           ([HrNo],[VersionNo],[IsReserve],[CustomerName],[CountryID]
           ,[BranchCode],[TC],[Type],[Status],[SendDate],[Deadline],[Extension]
           ,[Remark],[IsRead],[CreateDate],[CreateBy],[ModifyDate],[ModifyBy]
           ,[FirstOpenBy],[FirstOpenTime],[ConfirmedBy]
           ,[ConfirmedTime]
           ,[SendMail]
           ,[IsFree]
           ,[HotelRemark]
           ,[IsIDD])
select [HrNo],[VersionNo],[IsReserve],[CustomerName],[CountryID]
      ,[BranchCode],[TC],[Type],[Status],[SendDate],[Deadline],[Extension]
      ,[Remark],[IsRead],[CreateDate],[CreateBy],[ModifyDate],[ModifyBy]
      ,[FirstOpenBy],[FirstOpenTime],[ConfirmedBy]
      ,[ConfirmedTime]
      ,[SendMail]
      ,[IsFree]
      ,[HotelRemark]
      ,[IsIDD]
  FROM [UAT-TE2010HR].[dbo].[Gen_Reserves]
  
INSERT INTO [UAT-TEHR].[dbo].[Gen_ReservesHistory] 
           ([HrNo],[VersionNo],[IsReserve],[CustomerName],[CountryID]
           ,[BranchCode],[TC],[Type],[Status],[SendDate],[Deadline],[Extension]
           ,[Remark],[IsRead],[CreateDate],[CreateBy],[ModifyDate],[ModifyBy]
           ,[FirstOpenBy],[FirstOpenTime],[ConfirmedBy]
           ,[ConfirmedTime]
           ,[SendMail]
           ,[IsFree]
           ,[HotelRemark]
           ,[IsIDD])
select [HrNo],[VersionNo],[IsReserve],[CustomerName],[CountryID]
      ,[BranchCode],[TC],[Type],[Status],[SendDate],[Deadline],[Extension]
      ,[Remark],[IsRead],[CreateDate],[CreateBy],[ModifyDate],[ModifyBy]
      ,[FirstOpenBy],[FirstOpenTime],[ConfirmedBy]
      ,[ConfirmedTime]
      ,[SendMail]
      ,[IsFree]
      ,[HotelRemark]
      ,[IsIDD]
FROM [UAT-TE2010HR].[dbo].[Gen_ReservesHistory] 


