INSERT INTO [UAT-TEHR].[dbo].[Gen_ReservePaxs]
           ([PaxID]
           ,[HrNo]
           ,[VersionNo]
           ,[SeqNo]
           ,[Title]
           ,[PassengerCSName]
           ,[CreateDate]
           ,[CreateBy]
           ,[ModifyDate]
           ,[ModifyBy]
           ,[FirstName]
           ,[LastName])
SELECT [PaxID]
      ,[HrNo]
      ,[VersionNo]
      ,[SeqNo]
      ,[Title]
      ,[PassengerCSName]
      ,[CreateDate]
      ,[CreateBy]
      ,[ModifyDate]
      ,[ModifyBy]
      ,[FirstName]
      ,[LastName]
  FROM [UAT-TE2010HR].[dbo].[Gen_ReservePaxs]
  
  

INSERT INTO [UAT-TEHR].[dbo].[Gen_ReservePaxsHistory] 
           ([PaxID]
           ,[HrNo]
           ,[VersionNo]
           ,[SeqNo]
           ,[Title]
           ,[PassengerCSName]
           ,[CreateDate]
           ,[CreateBy]
           ,[ModifyDate]
           ,[ModifyBy]
           ,[FirstName]
           ,[LastName])
SELECT [PaxID]
      ,[HrNo]
      ,[VersionNo]
      ,[SeqNo]
      ,[Title]
      ,[PassengerCSName]
      ,[CreateDate]
      ,[CreateBy]
      ,[ModifyDate]
      ,[ModifyBy]
      ,[FirstName]
      ,[LastName]
  FROM [UAT-TE2010HR].[dbo].[Gen_ReservePaxsHistory] 

